# Generated by Django 4.0.3 on 2022-03-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_user_created_at_user_updated_at_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='unit',
        ),
    ]
