# Generated by Django 4.0.3 on 2022-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_remove_habit_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(['date', 'habit'], name='unique_for_habit_and_date'),
        ),
    ]
