# Generated by Django 4.0.3 on 2022-03-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0007_alter_dailyrecord_result'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyrecord',
            name='unique_for_habit_and_date',
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='unique_for_habit_and_date'),
        ),
    ]
